### Example Tutorial

In [73]:
import pandas as pd

import request_api as reqdata
import pandas_init as pd_init
from config.config import Weather_API_KEY

In [74]:
city = "Ankara"
country_code = 'TR'

lat,long = reqdata.get_lat_log(city, country_code)

In [75]:
# this variables is unix time, UTC time zone

startdate = 1606435200
enddate = 1704067140

In [76]:
current_response,forecast_response,historical_response = reqdata.request_init(lat,long,startdate,enddate)

In [77]:
forecast_response

{'coord': {'lon': 32.854, 'lat': 39.9208},
 'list': [{'main': {'aqi': 5},
   'components': {'co': 1068.12,
    'no': 75.1,
    'no2': 80.88,
    'o3': 0,
    'so2': 38.15,
    'pm2_5': 134.24,
    'pm10': 149.87,
    'nh3': 9.12},
   'dt': 1704488400},
  {'main': {'aqi': 5},
   'components': {'co': 947.95,
    'no': 55.43,
    'no2': 79.51,
    'o3': 0,
    'so2': 42.92,
    'pm2_5': 115.23,
    'pm10': 129.35,
    'nh3': 10.13},
   'dt': 1704492000},
  {'main': {'aqi': 5},
   'components': {'co': 767.71,
    'no': 30.85,
    'no2': 74.71,
    'o3': 0.03,
    'so2': 45.3,
    'pm2_5': 87.65,
    'pm10': 99.44,
    'nh3': 11.02},
   'dt': 1704495600},
  {'main': {'aqi': 4},
   'components': {'co': 607.49,
    'no': 11.51,
    'no2': 66.49,
    'o3': 0.63,
    'so2': 41.96,
    'pm2_5': 63.57,
    'pm10': 73.15,
    'nh3': 10.77},
   'dt': 1704499200},
  {'main': {'aqi': 3},
   'components': {'co': 514.03,
    'no': 2.46,
    'no2': 56.89,
    'o3': 3.93,
    'so2': 38.62,
    'pm2_5': 49.45,
    'pm10': 57.52,
    'nh3': 10.64},
   'dt': 1704502800},
  {'main': {'aqi': 3},
   'components': {'co': 460.63,
    'no': 0.37,
    'no2': 45.24,
    'o3': 12.34,
    'so2': 36.72,
    'pm2_5': 41.76,
    'pm10': 48.72,
    'nh3': 10.77},
   'dt': 1704506400},
  {'main': {'aqi': 3},
   'components': {'co': 423.91,
    'no': 0.12,
    'no2': 34.96,
    'o3': 22.17,
    'so2': 33.85,
    'pm2_5': 36.14,
    'pm10': 42.35,
    'nh3': 10.64},
   'dt': 1704510000},
  {'main': {'aqi': 3},
   'components': {'co': 407.22,
    'no': 0.1,
    'no2': 29.47,
    'o3': 28.61,
    'so2': 30.28,
    'pm2_5': 32.3,
    'pm10': 37.82,
    'nh3': 10.26},
   'dt': 1704513600},
  {'main': {'aqi': 3},
   'components': {'co': 473.98,
    'no': 1.54,
    'no2': 42.84,
    'o3': 14.31,
    'so2': 32.9,
    'pm2_5': 40.73,
    'pm10': 46.95,
    'nh3': 11.53},
   'dt': 1704517200},
  {'main': {'aqi': 4},
   'components': {'co': 614.17,
    'no': 19,
    'no2': 54.84,
    'o3': 1.42,
    'so2': 38.62,
    'pm2_5': 58.88,
    'pm10': 66.85,
    'nh3': 13.68},
   'dt': 1704520800},
  {'main': {'aqi': 5},
   'components': {'co': 747.68,
    'no': 45.15,
    'no2': 50.72,
    'o3': 7.24,
    'so2': 37.19,
    'pm2_5': 75.73,
    'pm10': 85.33,
    'nh3': 11.91},
   'dt': 1704524400},
  {'main': {'aqi': 5},
   'components': {'co': 801.09,
    'no': 55.88,
    'no2': 45.24,
    'o3': 12.52,
    'so2': 30.28,
    'pm2_5': 83.31,
    'pm10': 93.84,
    'nh3': 8.61},
   'dt': 1704528000},
  {'main': {'aqi': 5},
   'components': {'co': 787.74,
    'no': 53.64,
    'no2': 43.53,
    'o3': 16.99,
    'so2': 27.42,
    'pm2_5': 84.78,
    'pm10': 95.54,
    'nh3': 8.49},
   'dt': 1704531600},
  {'main': {'aqi': 2},
   'components': {'co': 370.5,
    'no': 8.83,
    'no2': 21.25,
    'o3': 56.51,
    'so2': 16.69,
    'pm2_5': 21.27,
    'pm10': 24.59,
    'nh3': 2.34},
   'dt': 1704535200},
  {'main': {'aqi': 2},
   'components': {'co': 300.41,
    'no': 4.64,
    'no2': 13.71,
    'o3': 65.09,
    'so2': 13.95,
    'pm2_5': 12.06,
    'pm10': 14.56,
    'nh3': 1.76},
   'dt': 1704538800},
  {'main': {'aqi': 2},
   'components': {'co': 273.71,
    'no': 3.21,
    'no2': 10.97,
    'o3': 68.67,
    'so2': 11.92,
    'pm2_5': 8.69,
    'pm10': 10.84,
    'nh3': 1.71},
   'dt': 1704542400},
  {'main': {'aqi': 2},
   'components': {'co': 330.45,
    'no': 5.92,
    'no2': 24.33,
    'o3': 50.78,
    'so2': 13.71,
    'pm2_5': 12.93,
    'pm10': 15.79,
    'nh3': 2.91},
   'dt': 1704546000},
  {'main': {'aqi': 2},
   'components': {'co': 447.27,
    'no': 10.17,
    'no2': 47.98,
    'o3': 20.39,
    'so2': 17.88,
    'pm2_5': 23.21,
    'pm10': 27.57,
    'nh3': 5},
   'dt': 1704549600},
  {'main': {'aqi': 3},
   'components': {'co': 547.41,
    'no': 18.33,
    'no2': 61.69,
    'o3': 1.13,
    'so2': 22.41,
    'pm2_5': 32.63,
    'pm10': 38.33,
    'nh3': 7.09},
   'dt': 1704553200},
  {'main': {'aqi': 3},
   'components': {'co': 620.84,
    'no': 31.29,
    'no2': 58.26,
    'o3': 0.01,
    'so2': 28.61,
    'pm2_5': 43.27,
    'pm10': 50.02,
    'nh3': 9.37},
   'dt': 1704556800},
  {'main': {'aqi': 4},
   'components': {'co': 660.9,
    'no': 34.87,
    'no2': 56.21,
    'o3': 0,
    'so2': 30.99,
    'pm2_5': 55.94,
    'pm10': 63.67,
    'nh3': 9.88},
   'dt': 1704560400},
  {'main': {'aqi': 4},
   'components': {'co': 680.92,
    'no': 31.74,
    'no2': 54.15,
    'o3': 0.01,
    'so2': 28.61,
    'pm2_5': 69.07,
    'pm10': 77.85,
    'nh3': 8.23},
   'dt': 1704564000},
  {'main': {'aqi': 5},
   'components': {'co': 667.57,
    'no': 23.25,
    'no2': 51.41,
    'o3': 0.05,
    'so2': 23.84,
    'pm2_5': 75.44,
    'pm10': 84.45,
    'nh3': 6.21},
   'dt': 1704567600},
  {'main': {'aqi': 5},
   'components': {'co': 634.19,
    'no': 15.2,
    'no2': 47.3,
    'o3': 0.24,
    'so2': 21.94,
    'pm2_5': 75.27,
    'pm10': 84.05,
    'nh3': 5.76},
   'dt': 1704571200},
  {'main': {'aqi': 4},
   'components': {'co': 600.82,
    'no': 10.39,
    'no2': 45.24,
    'o3': 0.65,
    'so2': 20.27,
    'pm2_5': 71.14,
    'pm10': 79.22,
    'nh3': 5.76},
   'dt': 1704574800},
  {'main': {'aqi': 4},
   'components': {'co': 547.41,
    'no': 5.42,
    'no2': 42.84,
    'o3': 1.99,
    'so2': 16.69,
    'pm2_5': 60.61,
    'pm10': 67.35,
    'nh3': 5.45},
   'dt': 1704578400},
  {'main': {'aqi': 3},
   'components': {'co': 473.98,
    'no': 1.33,
    'no2': 35.64,
    'o3': 7.42,
    'so2': 16.21,
    'pm2_5': 48.14,
    'pm10': 53.6,
    'nh3': 6.78},
   'dt': 1704582000},
  {'main': {'aqi': 3},
   'components': {'co': 417.23,
    'no': 0.21,
    'no2': 26.05,
    'o3': 16.99,
    'so2': 14.66,
    'pm2_5': 38.43,
    'pm10': 42.96,
    'nh3': 6.9},
   'dt': 1704585600},
  {'main': {'aqi': 3},
   'components': {'co': 383.85,
    'no': 0.07,
    'no2': 20.56,
    'o3': 23.6,
    'so2': 13.71,
    'pm2_5': 33.06,
    'pm10': 37.07,
    'nh3': 7.09},
   'dt': 1704589200},
  {'main': {'aqi': 3},
   'components': {'co': 367.17,
    'no': 0.05,
    'no2': 18.17,
    'o3': 26.82,
    'so2': 12.99,
    'pm2_5': 30.04,
    'pm10': 33.76,
    'nh3': 7.22},
   'dt': 1704592800},
  {'main': {'aqi': 3},
   'components': {'co': 357.15,
    'no': 0.06,
    'no2': 17.65,
    'o3': 27.9,
    'so2': 12.4,
    'pm2_5': 27.8,
    'pm10': 31.31,
    'nh3': 6.97},
   'dt': 1704596400},
  {'main': {'aqi': 3},
   'components': {'co': 357.15,
    'no': 0.11,
    'no2': 19.88,
    'o3': 26.82,
    'so2': 12.64,
    'pm2_5': 26.65,
    'pm10': 30.14,
    'nh3': 6.84},
   'dt': 1704600000},
  {'main': {'aqi': 3},
   'components': {'co': 427.25,
    'no': 1.48,
    'no2': 35.3,
    'o3': 13.23,
    'so2': 15.5,
    'pm2_5': 34.98,
    'pm10': 39.53,
    'nh3': 6.08},
   'dt': 1704603600},
  {'main': {'aqi': 3},
   'components': {'co': 554.09,
    'no': 14.53,
    'no2': 50.72,
    'o3': 1.48,
    'so2': 14.54,
    'pm2_5': 48.96,
    'pm10': 55.02,
    'nh3': 3.1},
   'dt': 1704607200},
  {'main': {'aqi': 3},
   'components': {'co': 594.14,
    'no': 24.14,
    'no2': 51.41,
    'o3': 6.62,
    'so2': 14.42,
    'pm2_5': 46.82,
    'pm10': 52.81,
    'nh3': 2.66},
   'dt': 1704610800},
  {'main': {'aqi': 3},
   'components': {'co': 494,
    'no': 17.43,
    'no2': 39.76,
    'o3': 22.35,
    'so2': 14.07,
    'pm2_5': 31.45,
    'pm10': 36.31,
    'nh3': 3.36},
   'dt': 1704614400},
  {'main': {'aqi': 2},
   'components': {'co': 353.81,
    'no': 7.49,
    'no2': 21.94,
    'o3': 49.35,
    'so2': 11.33,
    'pm2_5': 15.67,
    'pm10': 18.79,
    'nh3': 2.79},
   'dt': 1704618000},
  {'main': {'aqi': 2},
   'components': {'co': 243.66,
    'no': 1.59,
    'no2': 7.2,
    'o3': 75.1,
    'so2': 7.09,
    'pm2_5': 5.86,
    'pm10': 7.45,
    'nh3': 1.09},
   'dt': 1704621600},
  {'main': {'aqi': 2},
   'components': {'co': 236.99,
    'no': 1.1,
    'no2': 6.51,
    'o3': 77.96,
    'so2': 6.14,
    'pm2_5': 4.73,
    'pm10': 6.08,
    'nh3': 0.96},
   'dt': 1704625200},
  {'main': {'aqi': 2},
   'components': {'co': 230.31,
    'no': 0.7,
    'no2': 6.51,
    'o3': 77.96,
    'so2': 5.25,
    'pm2_5': 3.64,
    'pm10': 4.75,
    'nh3': 0.92},
   'dt': 1704628800},
  {'main': {'aqi': 2},
   'components': {'co': 230.31,
    'no': 0.45,
    'no2': 6.94,
    'o3': 75.82,
    'so2': 4.95,
    'pm2_5': 3.25,
    'pm10': 4.15,
    'nh3': 0.86},
   'dt': 1704632400},
  {'main': {'aqi': 2},
   'components': {'co': 230.31,
    'no': 0.24,
    'no2': 7.97,
    'o3': 72.96,
    'so2': 4.83,
    'pm2_5': 2.92,
    'pm10': 3.72,
    'nh3': 0.82},
   'dt': 1704636000},
  {'main': {'aqi': 2},
   'components': {'co': 233.65,
    'no': 0.02,
    'no2': 9.6,
    'o3': 69.38,
    'so2': 4.47,
    'pm2_5': 2.62,
    'pm10': 3.31,
    'nh3': 0.78},
   'dt': 1704639600},
  {'main': {'aqi': 2},
   'components': {'co': 240.33,
    'no': 0,
    'no2': 10.88,
    'o3': 67.23,
    'so2': 4.53,
    'pm2_5': 2.63,
    'pm10': 3.3,
    'nh3': 0.8},
   'dt': 1704643200},
  {'main': {'aqi': 2},
   'components': {'co': 247,
    'no': 0,
    'no2': 11.31,
    'o3': 65.8,
    'so2': 5.31,
    'pm2_5': 3.29,
    'pm10': 4.1,
    'nh3': 0.88},
   'dt': 1704646800},
  {'main': {'aqi': 2},
   'components': {'co': 253.68,
    'no': 0,
    'no2': 10.8,
    'o3': 65.09,
    'so2': 5.84,
    'pm2_5': 4.13,
    'pm10': 5.1,
    'nh3': 0.89},
   'dt': 1704650400},
  {'main': {'aqi': 2},
   'components': {'co': 253.68,
    'no': 0,
    'no2': 9.51,
    'o3': 64.37,
    'so2': 5.78,
    'pm2_5': 4.32,
    'pm10': 5.34,
    'nh3': 0.82},
   'dt': 1704654000},
  {'main': {'aqi': 2},
   'components': {'co': 250.34,
    'no': 0,
    'no2': 8.65,
    'o3': 64.37,
    'so2': 5.6,
    'pm2_5': 4.15,
    'pm10': 5.13,
    'nh3': 0.77},
   'dt': 1704657600},
  {'main': {'aqi': 2},
   'components': {'co': 247,
    'no': 0,
    'no2': 8.23,
    'o3': 64.37,
    'so2': 5.07,
    'pm2_5': 3.43,
    'pm10': 4.28,
    'nh3': 0.64},
   'dt': 1704661200},
  {'main': {'aqi': 2},
   'components': {'co': 236.99,
    'no': 0,
    'no2': 6.86,
    'o3': 64.37,
    'so2': 3.99,
    'pm2_5': 2.13,
    'pm10': 2.77,
    'nh3': 0.47},
   'dt': 1704664800},
  {'main': {'aqi': 2},
   'components': {'co': 233.65,
    'no': 0,
    'no2': 6.17,
    'o3': 63.66,
    'so2': 4.41,
    'pm2_5': 1.89,
    'pm10': 2.54,
    'nh3': 0.48},
   'dt': 1704668400},
  {'main': {'aqi': 2},
   'components': {'co': 233.65,
    'no': 0,
    'no2': 5.91,
    'o3': 62.23,
    'so2': 5.07,
    'pm2_5': 2.04,
    'pm10': 2.78,
    'nh3': 0.54},
   'dt': 1704672000},
  {'main': {'aqi': 2},
   'components': {'co': 236.99,
    'no': 0,
    'no2': 6,
    'o3': 60.08,
    'so2': 5.36,
    'pm2_5': 2,
    'pm10': 2.79,
    'nh3': 0.56},
   'dt': 1704675600},
  {'main': {'aqi': 1},
   'components': {'co': 240.33,
    'no': 0,
    'no2': 6.26,
    'o3': 58.65,
    'so2': 5.6,
    'pm2_5': 2.13,
    'pm10': 2.96,
    'nh3': 0.58},
   'dt': 1704679200},
  {'main': {'aqi': 1},
   'components': {'co': 243.66,
    'no': 0,
    'no2': 6.94,
    'o3': 57.22,
    'so2': 5.9,
    'pm2_5': 2.35,
    'pm10': 3.23,
    'nh3': 0.6},
   'dt': 1704682800},
  {'main': {'aqi': 1},
   'components': {'co': 250.34,
    'no': 0,
    'no2': 9,
    'o3': 55.79,
    'so2': 6.62,
    'pm2_5': 2.98,
    'pm10': 3.99,
    'nh3': 0.7},
   'dt': 1704686400},
  {'main': {'aqi': 1},
   'components': {'co': 290.39,
    'no': 0.01,
    'no2': 18.51,
    'o3': 46.49,
    'so2': 9.3,
    'pm2_5': 6.34,
    'pm10': 7.93,
    'nh3': 1.16},
   'dt': 1704690000},
  {'main': {'aqi': 2},
   'components': {'co': 357.15,
    'no': 0.44,
    'no2': 35.64,
    'o3': 28.25,
    'so2': 12.4,
    'pm2_5': 11.32,
    'pm10': 13.74,
    'nh3': 1.66},
   'dt': 1704693600},
  {'main': {'aqi': 2},
   'components': {'co': 383.85,
    'no': 3.1,
    'no2': 37.01,
    'o3': 25.03,
    'so2': 13.47,
    'pm2_5': 12.56,
    'pm10': 15.34,
    'nh3': 1.76},
   'dt': 1704697200},
  {'main': {'aqi': 1},
   'components': {'co': 347.14,
    'no': 3.13,
    'no2': 27.08,
    'o3': 34.33,
    'so2': 12.76,
    'pm2_5': 9.5,
    'pm10': 11.94,
    'nh3': 1.69},
   'dt': 1704700800},
  {'main': {'aqi': 1},
   'components': {'co': 297.07,
    'no': 1.57,
    'no2': 18.51,
    'o3': 45.42,
    'so2': 10.97,
    'pm2_5': 5.61,
    'pm10': 7.41,
    'nh3': 1.52},
   'dt': 1704704400},
  {'main': {'aqi': 2},
   'components': {'co': 233.65,
    'no': 0.48,
    'no2': 7.11,
    'o3': 67.95,
    'so2': 5.19,
    'pm2_5': 2.04,
    'pm10': 3.22,
    'nh3': 0.67},
   'dt': 1704708000},
  {'main': {'aqi': 2},
   'components': {'co': 230.31,
    'no': 0.7,
    'no2': 7.2,
    'o3': 72.96,
    'so2': 5.07,
    'pm2_5': 2.17,
    'pm10': 3.42,
    'nh3': 0.63},
   'dt': 1704711600},
  {'main': {'aqi': 2},
   'components': {'co': 230.31,
    'no': 0.85,
    'no2': 8.23,
    'o3': 73.67,
    'so2': 5.25,
    'pm2_5': 2.66,
    'pm10': 4.14,
    'nh3': 0.71},
   'dt': 1704715200},
  {'main': {'aqi': 2},
   'components': {'co': 240.33,
    'no': 0.88,
    'no2': 10.97,
    'o3': 70.1,
    'so2': 6.26,
    'pm2_5': 3.69,
    'pm10': 5.7,
    'nh3': 0.89},
   'dt': 1704718800},
  {'main': {'aqi': 2},
   'components': {'co': 257.02,
    'no': 0.58,
    'no2': 16.28,
    'o3': 62.94,
    'so2': 7.51,
    'pm2_5': 4.98,
    'pm10': 7.48,
    'nh3': 1.14},
   'dt': 1704722400},
  {'main': {'aqi': 1},
   'components': {'co': 277.04,
    'no': 0.06,
    'no2': 22.96,
    'o3': 55.08,
    'so2': 7.99,
    'pm2_5': 6.29,
    'pm10': 9.31,
    'nh3': 1.3},
   'dt': 1704726000},
  {'main': {'aqi': 2},
   'components': {'co': 343.8,
    'no': 0.25,
    'no2': 42.16,
    'o3': 33.62,
    'so2': 10.01,
    'pm2_5': 10.97,
    'pm10': 14.77,
    'nh3': 1.76},
   'dt': 1704729600},
  {'main': {'aqi': 2},
   'components': {'co': 447.27,
    'no': 2.49,
    'no2': 60.32,
    'o3': 10.28,
    'so2': 14.54,
    'pm2_5': 21.34,
    'pm10': 26.6,
    'nh3': 2.63},
   'dt': 1704733200},
  {'main': {'aqi': 3},
   'components': {'co': 514.03,
    'no': 6.71,
    'no2': 62.38,
    'o3': 2.82,
    'so2': 18.6,
    'pm2_5': 32.68,
    'pm10': 39.54,
    'nh3': 3.45},
   'dt': 1704736800},
  {'main': {'aqi': 3},
   'components': {'co': 554.09,
    'no': 8.94,
    'no2': 61.01,
    'o3': 1.34,
    'so2': 20.5,
    'pm2_5': 40.81,
    'pm10': 48.78,
    'nh3': 3.83},
   'dt': 1704740400},
  {'main': {'aqi': 3},
   'components': {'co': 547.41,
    'no': 6.09,
    'no2': 58.95,
    'o3': 2.57,
    'so2': 19.31,
    'pm2_5': 41.23,
    'pm10': 49.17,
    'nh3': 3.42},
   'dt': 1704744000},
  {'main': {'aqi': 3},
   'components': {'co': 487.33,
    'no': 1.9,
    'no2': 53.47,
    'o3': 9.21,
    'so2': 15.5,
    'pm2_5': 32.36,
    'pm10': 38.86,
    'nh3': 2.5},
   'dt': 1704747600},
  {'main': {'aqi': 2},
   'components': {'co': 413.9,
    'no': 0.29,
    'no2': 43.18,
    'o3': 19.67,
    'so2': 10.25,
    'pm2_5': 20.9,
    'pm10': 25.48,
    'nh3': 1.57},
   'dt': 1704751200},
  {'main': {'aqi': 2},
   'components': {'co': 387.19,
    'no': 0.14,
    'no2': 37.7,
    'o3': 22.89,
    'so2': 8.46,
    'pm2_5': 17.08,
    'pm10': 20.85,
    'nh3': 1.43},
   'dt': 1704754800},
  {'main': {'aqi': 2},
   'components': {'co': 367.17,
    'no': 0.05,
    'no2': 30.5,
    'o3': 28.97,
    'so2': 8.23,
    'pm2_5': 15.29,
    'pm10': 18.68,
    'nh3': 1.5},
   'dt': 1704758400},
  {'main': {'aqi': 2},
   'components': {'co': 357.15,
    'no': 0.03,
    'no2': 26.05,
    'o3': 32.19,
    'so2': 8.35,
    'pm2_5': 15.76,
    'pm10': 18.89,
    'nh3': 1.54},
   'dt': 1704762000},
  {'main': {'aqi': 2},
   'components': {'co': 350.48,
    'no': 0.02,
    'no2': 23.31,
    'o3': 33.26,
    'so2': 8.58,
    'pm2_5': 16.71,
    'pm10': 19.7,
    'nh3': 1.41},
   'dt': 1704765600},
  {'main': {'aqi': 2},
   'components': {'co': 343.8,
    'no': 0.02,
    'no2': 21.76,
    'o3': 34.69,
    'so2': 9.06,
    'pm2_5': 16.42,
    'pm10': 19.2,
    'nh3': 1.27},
   'dt': 1704769200},
  {'main': {'aqi': 2},
   'components': {'co': 340.46,
    'no': 0.03,
    'no2': 23.65,
    'o3': 36.12,
    'so2': 10.73,
    'pm2_5': 15.56,
    'pm10': 18.28,
    'nh3': 1.36},
   'dt': 1704772800},
  {'main': {'aqi': 3},
   'components': {'co': 440.6,
    'no': 2.01,
    'no2': 47.3,
    'o3': 13.41,
    'so2': 18.84,
    'pm2_5': 27.43,
    'pm10': 31.64,
    'nh3': 3.14},
   'dt': 1704776400},
  {'main': {'aqi': 3},
   'components': {'co': 627.52,
    'no': 29.95,
    'no2': 64.43,
    'o3': 0.21,
    'so2': 32.42,
    'pm2_5': 48.4,
    'pm10': 54.83,
    'nh3': 6.4},
   'dt': 1704780000},
  {'main': {'aqi': 4},
   'components': {'co': 787.74,
    'no': 60.8,
    'no2': 69.23,
    'o3': 0.39,
    'so2': 48.16,
    'pm2_5': 65.8,
    'pm10': 73.7,
    'nh3': 9.75},
   'dt': 1704783600},
  {'main': {'aqi': 4},
   'components': {'co': 794.41,
    'no': 61.69,
    'no2': 68.55,
    'o3': 1.21,
    'so2': 50.07,
    'pm2_5': 68.73,
    'pm10': 76.59,
    'nh3': 9.88},
   'dt': 1704787200},
  {'main': {'aqi': 4},
   'components': {'co': 687.6,
    'no': 45.6,
    'no2': 63.75,
    'o3': 2.64,
    'so2': 40.53,
    'pm2_5': 57.54,
    'pm10': 64.37,
    'nh3': 7.73},
   'dt': 1704790800},
  {'main': {'aqi': 3},
   'components': {'co': 560.76,
    'no': 28.61,
    'no2': 58.26,
    'o3': 5.14,
    'so2': 27.9,
    'pm2_5': 41.8,
    'pm10': 47.23,
    'nh3': 5.38},
   'dt': 1704794400},
  {'main': {'aqi': 3},
   'components': {'co': 480.65,
    'no': 19.45,
    'no2': 53.47,
    'o3': 7.42,
    'so2': 20.03,
    'pm2_5': 30.82,
    'pm10': 35.29,
    'nh3': 3.9},
   'dt': 1704798000},
  {'main': {'aqi': 2},
   'components': {'co': 413.9,
    'no': 10.62,
    'no2': 47.3,
    'o3': 12.16,
    'so2': 15.26,
    'pm2_5': 21.04,
    'pm10': 24.5,
    'nh3': 2.69},
   'dt': 1704801600},
  {'main': {'aqi': 2},
   'components': {'co': 343.8,
    'no': 4.14,
    'no2': 36.33,
    'o3': 24.68,
    'so2': 11.8,
    'pm2_5': 11.96,
    'pm10': 14.53,
    'nh3': 1.98},
   'dt': 1704805200},
  {'main': {'aqi': 2},
   'components': {'co': 360.49,
    'no': 3.05,
    'no2': 43.53,
    'o3': 15.74,
    'so2': 11.8,
    'pm2_5': 12.14,
    'pm10': 15.06,
    'nh3': 2.41},
   'dt': 1704808800},
  {'main': {'aqi': 2},
   'components': {'co': 423.91,
    'no': 8.94,
    'no2': 54.84,
    'o3': 2.75,
    'so2': 14.42,
    'pm2_5': 15.64,
    'pm10': 19.14,
    'nh3': 3.07},
   'dt': 1704812400},
  {'main': {'aqi': 2},
   'components': {'co': 473.98,
    'no': 17.43,
    'no2': 54.84,
    'o3': 0.24,
    'so2': 16.93,
    'pm2_5': 19.92,
    'pm10': 24.01,
    'nh3': 3.64},
   'dt': 1704816000},
  {'main': {'aqi': 2},
   'components': {'co': 447.27,
    'no': 10.84,
    'no2': 50.72,
    'o3': 1.11,
    'so2': 15.26,
    'pm2_5': 19.57,
    'pm10': 23.77,
    'nh3': 3.45},
   'dt': 1704819600},
  {'main': {'aqi': 2},
   'components': {'co': 377.18,
    'no': 2.26,
    'no2': 39.41,
    'o3': 8.32,
    'so2': 11.56,
    'pm2_5': 14.73,
    'pm10': 18.43,
    'nh3': 2.69},
   'dt': 1704823200},
  {'main': {'aqi': 2},
   'components': {'co': 323.77,
    'no': 0.55,
    'no2': 24.33,
    'o3': 14.66,
    'so2': 8.11,
    'pm2_5': 10.34,
    'pm10': 12.9,
    'nh3': 1.69},
   'dt': 1704826800},
  {'main': {'aqi': 1},
   'components': {'co': 303.75,
    'no': 0.5,
    'no2': 16.11,
    'o3': 13.77,
    'so2': 5.9,
    'pm2_5': 7.15,
    'pm10': 8.9,
    'nh3': 1.17},
   'dt': 1704830400}]}

In [78]:
df_current = pd_init.create_dataframe_from_response(current_response['list'])

In [79]:
df_current

,datetimes,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NO_μg/m3,concentration_of_NO2_μg/m3,concentration_of_O3_μg/m3,concentration_of_SO2_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_PM10_μg/m3,concentration_of_NH3_μg/m3
0,2024-01-05 21:46:50,5,947.95,55.43,79.51,0,42.92,115.23,129.35,10.13

In [80]:
df_forecast = pd_init.create_dataframe_from_response(forecast_response['list'])

In [81]:
df_forecast.sample(3)

,datetimes,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NO_μg/m3,concentration_of_NO2_μg/m3,concentration_of_O3_μg/m3,concentration_of_SO2_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_PM10_μg/m3,concentration_of_NH3_μg/m3
5,2024-01-06 02:00:00,3,460.63,0.37,45.24,12.34,36.72,41.76,48.72,10.77
44,2024-01-07 17:00:00,2,247.00,0.00,11.31,65.80,5.31,3.29,4.10,0.88
87,2024-01-09 12:00:00,2,413.90,10.62,47.30,12.16,15.26,21.04,24.50,2.69

In [82]:
df_historical = pd_init.create_dataframe_from_response(historical_response['list'])

In [83]:
df_historical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18216 entries, 0 to 18215
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   datetimes                     18216 non-null  datetime64[ns]
 1   air_quality_index             18216 non-null  int64
 2   concentration_of_CO_μg/m3     18216 non-null  float64
 3   concentration_of_NO_μg/m3     18216 non-null  float64
 4   concentration_of_NO2_μg/m3    18216 non-null  float64
 5   concentration_of_O3_μg/m3     18216 non-null  float64
 6   concentration_of_SO2_μg/m3    18216 non-null  float64
 7   concentration_of_PM2_5_μg/m3  18216 non-null  float64
 8   concentration_of_PM10_μg/m3   18216 non-null  float64
 9   concentration_of_NH3_μg/m3    18216 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(1)
memory usage: 1.4 MB

In [84]:
df_historical.sample(3)

,datetimes,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NO_μg/m3,concentration_of_NO2_μg/m3,concentration_of_O3_μg/m3,concentration_of_SO2_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_PM10_μg/m3,concentration_of_NH3_μg/m3
1048,2021-01-07 17:00:00,5,1642.23,216.37,105.56,0.00,103.00,178.38,202.82,26.35
2421,2021-03-06 22:00:00,4,427.25,0.07,41.81,31.47,13.59,30.33,33.73,5.89
7129,2021-09-19 02:00:00,2,390.53,0.06,27.08,20.03,15.14,16.63,22.07,17.48

In [85]:
#This dataframe is not include NAN values
df_historical.isna().sum()

datetimes                       0
air_quality_index               0
concentration_of_CO_μg/m3       0
concentration_of_NO_μg/m3       0
concentration_of_NO2_μg/m3      0
concentration_of_O3_μg/m3       0
concentration_of_SO2_μg/m3      0
concentration_of_PM2_5_μg/m3    0
concentration_of_PM10_μg/m3     0
concentration_of_NH3_μg/m3      0
dtype: int64

In [86]:
df_historical.duplicated().sum()

0

In [87]:
selected_columns = df_historical.columns.difference(["datetimes"])
df_historical.loc[:,selected_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
air_quality_index,18216.0,2.589866,1.456344,1.00,1.0000,2.000,4.0000,5.00
concentration_of_CO_μg/m3,18216.0,398.079030,258.573613,143.53,226.9700,293.730,480.6500,2056.12
concentration_of_NH3_μg/m3,18216.0,6.214997,7.592663,0.00,1.6300,3.290,7.4700,68.90
concentration_of_NO2_μg/m3,18216.0,27.613048,25.764210,0.90,6.8600,18.340,42.5000,172.73
concentration_of_NO_μg/m3,18216.0,13.924632,30.011513,0.00,0.0600,0.880,10.6200,268.22
concentration_of_O3_μg/m3,18216.0,47.294037,38.901333,0.00,9.3000,45.060,75.1000,217.44
concentration_of_PM10_μg/m3,18216.0,31.764900,39.607222,0.61,5.9475,14.685,42.3125,283.36
concentration_of_PM2_5_μg/m3,18216.0,26.596363,35.258204,0.50,4.9275,11.390,33.1425,261.10
concentration_of_SO2_μg/m3,18216.0,14.583550,15.734018,0.75,4.5900,8.820,18.3600,127.79

In [88]:
df_historical.loc[:,selected_columns].corr()

,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NH3_μg/m3,concentration_of_NO2_μg/m3,concentration_of_NO_μg/m3,concentration_of_O3_μg/m3,concentration_of_PM10_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_SO2_μg/m3
air_quality_index,1.000000,0.782763,0.595225,0.747688,0.602036,-0.483964,0.821255,0.805870,0.704038
concentration_of_CO_μg/m3,0.782763,1.000000,0.667768,0.884742,0.894426,-0.661017,0.919693,0.935577,0.854604
concentration_of_NH3_μg/m3,0.595225,0.667768,1.000000,0.655465,0.472267,-0.513022,0.647455,0.649790,0.695915
concentration_of_NO2_μg/m3,0.747688,0.884742,0.655465,1.000000,0.704716,-0.728872,0.786503,0.795326,0.809778
concentration_of_NO_μg/m3,0.602036,0.894426,0.472267,0.704716,1.000000,-0.471642,0.776419,0.789208,0.739039
concentration_of_O3_μg/m3,-0.483964,-0.661017,-0.513022,-0.728872,-0.471642,1.000000,-0.554044,-0.567531,-0.525958
concentration_of_PM10_μg/m3,0.821255,0.919693,0.647455,0.786503,0.776419,-0.554044,1.000000,0.987296,0.817587
concentration_of_PM2_5_μg/m3,0.805870,0.935577,0.649790,0.795326,0.789208,-0.567531,0.987296,1.000000,0.834024
concentration_of_SO2_μg/m3,0.704038,0.854604,0.695915,0.809778,0.739039,-0.525958,0.817587,0.834024,1.000000

In [89]:
df_historical['years'] = df_historical['datetimes'].dt.year
df_historical['months'] = df_historical['datetimes'].dt.strftime('%B')
df_historical['days'] = df_historical['datetimes'].dt.day

# Sütun sırasını değiştirmek için sütun isimlerini kullanmadan, sadece sırayı belirtmek:
df_historical = df_historical[['datetimes', 'years','months','days'] + [col for col in df_historical.columns if col not in ['datetimes', 'years','months','days']]]

In [90]:
df_historical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18216 entries, 0 to 18215
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   datetimes                     18216 non-null  datetime64[ns]
 1   years                         18216 non-null  int32
 2   months                        18216 non-null  object
 3   days                          18216 non-null  int32
 4   air_quality_index             18216 non-null  int64
 5   concentration_of_CO_μg/m3     18216 non-null  float64
 6   concentration_of_NO_μg/m3     18216 non-null  float64
 7   concentration_of_NO2_μg/m3    18216 non-null  float64
 8   concentration_of_O3_μg/m3     18216 non-null  float64
 9   concentration_of_SO2_μg/m3    18216 non-null  float64
 10  concentration_of_PM2_5_μg/m3  18216 non-null  float64
 11  concentration_of_PM10_μg/m3   18216 non-null  float64
 12  concentration_of_NH3_μg/m3    18216 non-null  float64
dtypes: datetime64[ns](1), float64(8), int32(2), int64(1), object(1)
memory usage: 1.7+ MB

In [91]:
df_historical.nunique()

datetimes                       18216
years                               4
months                             12
days                               31
air_quality_index                   5
concentration_of_CO_μg/m3         293
concentration_of_NO_μg/m3         670
concentration_of_NO2_μg/m3        534
concentration_of_O3_μg/m3         628
concentration_of_SO2_μg/m3        509
concentration_of_PM2_5_μg/m3     6536
concentration_of_PM10_μg/m3      7216
concentration_of_NH3_μg/m3        493
dtype: int64

In [92]:
df_historical.head(5)

,datetimes,years,months,days,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NO_μg/m3,concentration_of_NO2_μg/m3,concentration_of_O3_μg/m3,concentration_of_SO2_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_PM10_μg/m3,concentration_of_NH3_μg/m3
0,2020-11-25 01:00:00,2020,November,25,2,223.64,0.00,6.77,52.21,6.02,10.13,11.62,3.36
1,2020-11-25 02:00:00,2020,November,25,1,220.30,0.00,6.26,52.21,6.26,8.20,9.52,2.88
2,2020-11-25 03:00:00,2020,November,25,1,223.64,0.01,7.63,50.07,7.15,7.71,9.06,3.10
3,2020-11-25 04:00:00,2020,November,25,1,233.65,0.02,10.80,46.49,6.20,7.91,9.36,1.95
4,2020-11-25 05:00:00,2020,November,25,2,277.04,0.13,22.96,35.41,7.99,11.64,13.74,1.81

In [93]:
df_historical.tail(5)

,datetimes,years,months,days,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NO_μg/m3,concentration_of_NO2_μg/m3,concentration_of_O3_μg/m3,concentration_of_SO2_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_PM10_μg/m3,concentration_of_NH3_μg/m3
18211,2022-12-31 20:00:00,2022,December,31,5,1014.71,65.27,85.00,0.00,62.94,144.24,157.78,19.00
18212,2022-12-31 21:00:00,2022,December,31,5,934.60,46.94,80.88,0.00,63.90,138.33,151.04,21.03
18213,2022-12-31 22:00:00,2022,December,31,5,834.47,33.97,76.09,0.00,56.27,126.45,137.89,21.03
18214,2022-12-31 23:00:00,2022,December,31,5,754.36,22.80,70.60,0.02,48.64,113.56,123.61,20.27
18215,2023-01-01 00:00:00,2023,January,1,5,674.25,13.08,64.43,0.12,41.48,101.67,110.43,18.75

In [94]:
selected_values = df_historical.columns.difference(["datetimes","months","days"])
df_historical.loc[:,selected_values].groupby("years").mean()

,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NH3_μg/m3,concentration_of_NO2_μg/m3,concentration_of_NO_μg/m3,concentration_of_O3_μg/m3,concentration_of_PM10_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_SO2_μg/m3
years,,,,,,,,,
2020,3.811725,627.273687,7.580349,46.997170,36.361477,17.980688,72.828557,65.102864,28.720654
2021,2.535256,392.617370,6.071316,27.192101,12.486876,47.994676,29.617624,24.458871,13.667823
2022,2.518971,379.939043,6.218673,26.035634,13.070301,49.613325,29.699778,24.785701,14.052043
2023,5.000000,674.250000,18.750000,64.430000,13.080000,0.120000,110.430000,101.670000,41.480000

In [96]:
df_historical.groupby(["years","months"]).mean().reset_index()

,years,months,datetimes,days,air_quality_index,concentration_of_CO_μg/m3,concentration_of_NO_μg/m3,concentration_of_NO2_μg/m3,concentration_of_O3_μg/m3,concentration_of_SO2_μg/m3,concentration_of_PM2_5_μg/m3,concentration_of_PM10_μg/m3,concentration_of_NH3_μg/m3
0,2020,December,2020-12-16 11:30:00.000000000,16.000000,3.836022,649.209919,39.484556,47.350417,17.122984,28.506062,68.523696,76.631035,7.119247
1,2020,November,2020-11-28 00:00:00.000000000,27.517483,3.685315,513.143916,20.112727,45.159301,22.443147,29.837133,47.304965,53.045035,9.979371
2,2021,April,2021-04-15 23:30:00.000000000,15.500000,2.525000,351.280125,7.665583,24.545097,55.047069,10.855639,18.851889,28.420931,6.265181
3,2021,August,2021-08-16 11:30:00.000000000,16.000000,1.946237,276.095995,2.673105,12.004812,78.966734,5.253212,8.719234,12.865901,3.650309
4,2021,December,2021-12-16 11:30:00.000000000,16.000000,2.973118,481.311371,16.949785,34.767433,24.160726,20.056116,34.282446,40.078911,4.606089
5,2021,February,2021-02-14 23:30:00.000000000,14.500000,3.508929,575.726920,25.691622,46.098646,33.234658,25.759732,55.880997,63.215432,13.711429
6,2021,January,2021-01-16 02:40:00.000000000,15.631944,3.134722,468.179681,15.494722,37.189250,28.274875,21.741944,38.991000,44.780736,5.752611
7,2021,July,2021-07-16 11:30:00.000000000,16.000000,1.772849,214.181895,2.551734,9.503320,73.554382,3.820282,6.890134,9.632661,2.517728
8,2021,June,2021-06-15 23:30:00.000000000,15.500000,1.838889,279.098764,10.375778,21.208958,48.789889,7.733611,9.401528,11.119542,3.976639
9,2021,March,2021-03-16 11:30:00.000000000,16.000000,2.696237,425.247755,10.800645,31.326398,48.448185,14.629247,27.619879,31.746048,11.731707
10,2021,May,2021-05-16 11:30:00.000000000,16.000000,2.348118,289.344530,6.116237,20.195941,63.723051,8.778091,14.024530,21.299301,4.137366
11,2021,November,2021-11-15 23:30:00.000000000,15.500000,3.402778,589.118292,32.668403,42.608236,23.635375,25.039458,49.508403,56.601625,7.548333
12,2021,October,2021-10-16 11:30:00.000000000,16.000000,2.536290,443.473978,15.585793,30.886250,36.162312,13.910565,22.400511,26.423522,5.165121
13,2021,September,2021-09-15 23:30:00.000000000,15.500000,1.836111,338.091389,4.824222,18.046917,59.719944,7.760750,10.124597,12.655375,4.456611
14,2022,April,2022-04-15 23:30:00.000000000,15.500000,2.723611,355.855292,6.794306,23.699389,63.343458,11.483319,20.809222,32.081319,8.611431
15,2022,August,2022-08-16 11:30:00.000000000,16.000000,1.864247,238.087231,2.116290,10.981277,78.958602,5.417863,8.220860,10.462151,3.417728
16,2022,December,2022-12-16 14:49:17.142856960,16.138393,3.909226,684.052634,45.822351,46.484717,13.843438,32.045699,71.701220,79.948452,8.449985
17,2022,February,2022-02-14 18:34:26.666666496,14.294753,3.344136,552.256065,19.570556,42.220802,34.304846,24.357083,46.536713,52.189028,11.944522
18,2022,January,2022-01-16 05:52:00.000000000,15.765278,3.101389,506.914236,18.991500,37.490681,25.969403,23.787472,37.127458,41.896292,6.245986
19,2022,July,2022-07-16 03:58:57.931034368,15.686782,1.599138,184.407227,1.304368,6.997759,76.143204,3.290259,4.839727,5.448908,2.140115
20,2022,June,2022-06-15 23:30:00.000000000,15.500000,1.562500,225.627931,3.894986,12.679736,59.396764,4.836639,6.577542,9.329819,2.313278
21,2022,March,2022-03-16 11:30:00.000000000,16.000000,2.334677,381.722876,4.413535,23.230175,60.819651,12.003952,16.796680,20.280121,10.110121
22,2022,May,2022-05-16 11:30:00.000000000,16.000000,2.072581,289.543495,6.353535,18.282634,58.344476,7.677997,11.014247,15.250309,4.468454
23,2022,November,2022-11-15 23:30:00.000000000,15.500000,3.313889,498.496722,26.120889,39.232167,25.121833,20.193792,43.169861,50.429028,6.328125
24,2022,October,2022-10-16 11:30:00.000000000,16.000000,2.341398,360.282460,14.867944,28.349866,36.707930,13.347433,21.533790,25.776398,4.902648
25,2022,September,2022-09-15 23:30:00.000000000,15.500000,2.254167,321.347903,9.852319,25.902222,58.162542,12.646389,15.124931,19.663653,6.342931
26,2023,January,2023-01-01 00:00:00.000000000,1.000000,5.000000,674.250000,13.080000,64.430000,0.120000,41.480000,101.670000,110.430000,18.750000